version: '3.8'

services:
  # 后端服务
  backend:
    build: ./backend
    container_name: catiecli-backend
    ports:
      - '${PORT:-5001}:${PORT:-5001}'
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PORT=${PORT:-5001}
    restart: unless-stopped
